### ISSUE TITLE
Move to syntax-tree org

### ISSUE THREAD

**Issue by wooorm** [syntax-tree/mdast-util-toc#45]
@BarryThePenguin This is totally up to you, but by moving this repo to the [syntax-tree](https://github.com/syntax-tree) it’s easier for more people to help: shared code responsibility and more people that can publish (once I have an npm org set up), meaning less of a bus factor!

But: it’s up to you, it’s also fine where it is!

**Comment by BarryThePenguin** [comment]
I think this is a great idea 👍

Is there anything that needs changing first before the move (CI, Licensing, etc..)? Or can I just hit the transfer button?

**Comment by wooorm** [comment]
@BarryThePenguin Ping! I just did a refactor btw to give everything a nice polish after a few years of not getting much attention.

**Comment by BarryThePenguin** [comment]
Done! Was a bit slow 💦

**Comment by wooorm** [comment]
@BarryThePenguin Awesome, thanks @BarryThePenguin!! 🎉
