### ISSUE TITLE
Publishing latest version

### ISSUE THREAD

**Issue by BarryThePenguin** [syntax-tree/mdast-util-toc#55]
I tried publishing a version with the latest changes, but looks like I no longer have permissions to do that. I'm not fully across the latest governance changes, so happy to leave this up to whoever has publish permissions

All that's needed is someone running `npm publish` @ChristianMurphy @wooorm (I think!)

Thanks! 😊

**Comment by ChristianMurphy** [comment]
It appears I do not have publish access.
@syntax-tree/core anyone with access available to publish the release?

**Comment by wooorm** [comment]
Published, thanks for preparing the release @BarryThePenguin!
