### ISSUE TITLE
[Feature Request] Opting-out of phrasing content inclusion

### ISSUE THREAD

**Issue by altano** [syntax-tree/mdast-util-toc#67]
In https://github.com/syntax-tree/mdast-util-toc/pull/58 support was added to include phrasing content. Unfortunately, we sometimes might not always want this behavior.

# My use case

I'm using `gatsby-remark-table-of-contents` on a personal blog which uses `mdast-util-toc` under the covers. I would sometimes like to include images (custom React components in my MDX) in the headings, but I would NOT want to extract these into the table of contents. Currently my MDX looks like:

```mdx
### Never Pause Here <Chrome />

When you right-click the gutter and select "Never Pause Here," Chrome creates a conditional breakpoint that is `false` and never passes. This makes it so that the debugger will never pause on this line.
```

This creates a TOC entry that is just literally the string `"Never Pause Here <Chrome />"` when I would like it to be `"Never Pause Here"`.

It would be lovely if including phrasing content was an option that I could opt-out of.

**Comment by wooorm** [comment]
- How would that space also be removed (`'Here'` instead of `'Here '`)?
- What if you’d like some to be ignored, some to be included?
- Could this be solved by using a wrapping component?
  ```md

**Comment by altano** [comment]
Excellent questions! How would I get the wrapping component to render one way (without phrasing content) during the mdast-util-toc scan and another (with phrasing content) during the actual page rendering?

**Comment by wooorm** [comment]
Well, CSS could do the wrapping component maybe? Display the icon next to the heading?

The question to me is: is the icon part of the heading, or does it belong close to it? Should screenreader users and robots also read the icon as part of the heading?

**Comment by wooorm** [comment]
@altano What do you think re my previous comment?

**Comment by wooorm** [comment]
Going to close this as it’s stranded while not yet clear whether the current behavior is a bug. If someone finds this and has more ideas on this, feel free to open a new issue referencing this one!

**Comment by helloworld** [comment]
Hey! I'm running into the same issue. I'm using `rehype-slug` and `mdast-util-toc` alongside each other. I'm using the former as an MDX plugin to add slugs to my HTML, and the latter to extract out a table of contents so I can render it in the sidebar of the page. 

In 99% of cases, the slugs generated by the two libraries are the same and this setup works great. However, just like in the original issue, I have some headers that look like this:

```
### Dynamic fan-out <Experimental/>

### <Check /> Environment-specific hooks using modes
```

For these two headers, `rehype-slug` produces the following anchor links:

```
#dynamic-fan-out

#environment-specific-hooks-using-modes
```

However, `mdast-util-toc` produces:

```
#dynamic-fan-out-experimental

#check-environment-specific-hooks-using-modes
```

Interestingly, the titles produced by `mdhast-util-toc` don't include the text of the MDX components, only the slugs do. The titles look like:

```
Dynamic fan-out
Environment-specific hooks using modes
```

If you look at the underlying nodes for the header, they look like this: 

```
[
  {
    type: 'text',
    value: 'Dynamic fan-out ',
    position: { start: [Object], end: [Object] }
  },
  {
    type: 'html',
    value: '<Experimental/>',
    position: { start: [Object], end: [Object] }
  }
]
```

It would be great to have some sort of hook or option to get some consistency across `rehype-slug` and this library. Even ignoring `rehype-slug`, it feels like there should be some consistency between the title and slug when using this library in isolation. 

Here are pointers to how I'm using it in my project specifically in case the additional context helps. 

`rehype-slug`: 

- Definition: https://github.com/dagster-io/dagster/blob/master/docs/next/components/mdx/rehypePlugins.ts#L8-L31
- Usage: https://github.com/dagster-io/dagster/blob/master/docs/next/pages/%5B...page%5D.tsx#L354-L356

`mdast-util-toc`: https://github.com/dagster-io/dagster/blob/master/docs/next/pages/%5B...page%5D.tsx#L342-L345


Sorry for reviving such an old issue! I might be approaching this the wrong way completely or this problem might be out of scope for this plugin specifically, so please feel free to direct me away if so. 

Also, thank you so much for such a great ecosystem of plugins and tooling. Using MDX with the unified ecosystem has been nothing much amazing.
