### ISSUE TITLE
If heading already has a anchor, keep that one instead of creating a new one

### ISSUE THREAD

**Issue by stevemarksd** [syntax-tree/mdast-util-toc#68]
I prefer to manually create the anchors.

`## [Title 3](#title-2)`

your code will mark it as #title-3 in the toc, breaking the whole thing :)

**Comment by wooorm** [comment]
Please do not delete issue templates. They help us help you. It [again](https://spectrum.chat/unified/rehype/hi-how-to-simply-use-rehype-react-without-all-the-ton-of-dependencies~2462185e-75d5-4118-870c-a5d3d6b9cb62) shows an enormous lack of appreciation of our time.

[This project takes existing IDs](https://github.com/syntax-tree/mdast-util-toc/blob/7bbc91610bd349ea35a0f9461d3e8b1d12d1abcb/lib/search.js#L49).

[`remark-slug`](https://github.com/remarkjs/remark-slug/blob/97021c9661c25173abe7a6ddb0f83fe304de1c52/index.js#L24) doesn’t overwrite existing IDs.

[`rehype-slug`](https://github.com/rehypejs/rehype-slug/blob/76f382383e9af5a87fec7470b66b08e9598901b5/index.js#L21) does not overwrite existing IDs either.

You are creating a link to `title-2`. Not an ID. [GitHub creates a `title-3` anchor too](https://gist.github.com/wooorm/0976364caea20466d878d8a3323180f4#title-3).
